### PR TITLE
feat: nix package

### PR DESCRIPTION
**Pull request by tulilirockz**
This PR should add a proper nix package for this project.

I think that it might benefit this project by making it so anyone with the nix binary installed in their system can just run this project without worrying about compiling anything or whatever else! Just makes it so its guaranteed someone can use this.

### CODE REVIEW

**Comment by HikariKnight** [comment]
Will quickpassthrough actually generate a working config for nix though?
Because if it does not then we will have to write checks to provide the correct configs, as i know nothing about nix.

**Comment by tulilirockz** [comment]
It should! Considering Nix is a cross distro package manager, it should run just like a pre-compiled binary.... but using Nix!

**Comment by tulilirockz** [comment]
Welp, I guess this PR should be closed considering the stuff we talked about

**Comment by HikariKnight** [comment]
Sad days, i like being able to support as much as possible where it makes sense.
Thanks for trying!

**Pull request closed without merging**
